# Understanding of the Matrix

In [4]:
# We are using Libary of NumPy

import numpy as np

In [5]:
# Creating the Matrix
matrix = np.matrix([[1,2,3],[4,5,6]])
matrix

matrix([[1, 2, 3],
        [4, 5, 6]])

In [6]:
# Creating the Array
array = np.array([[1,2,3],[4,5,6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
# Finding the Type of the 

print(f"The Type of the Matrix is :{type(matrix)}")

The Type of the Matrix is :<class 'numpy.matrix'>


In [11]:
# Finding the Type of the 

print(f"The Type of the Matrix is :{type(array)}")

The Type of the Matrix is :<class 'numpy.ndarray'>


# Arthematic Operation on the Matrix

In [14]:
# Addition
add = matrix + matrix
add

matrix([[ 2,  4,  6],
        [ 8, 10, 12]])

In [15]:
# Subtraction
sub = matrix - matrix
sub

matrix([[0, 0, 0],
        [0, 0, 0]])

# Multiplication of the Matrix

In [17]:
muti = matrix * matrix
muti

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

"""Rules for the Multiplication of the matrix """"

Number of the Columns equal to number of the Rows in another matrix

In [23]:
# Multiplication of the 2x2 Matrix
matrix_1 = np.matrix([[1,2],[4,5]])

muti = matrix_1 * matrix_1
muti

matrix([[ 9, 12],
        [24, 33]])

In [28]:
# Multiplication of  3x3 matrices

# Two method

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

print("Matrix A:\n", A)
print()
print("Matrix B:\n", B)
print("\n The Dot Matrix of the A and B are:")
print(A*B)


Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

 The Dot Matrix of the A and B are:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [29]:
# Perform matrix multiplication using dot product
result = np.dot(A, B)

# Print the result
print("Matrix A:\n", A)
print()
print("Matrix B:\n", B)
print()
print("\nDot product of A and B:\n", result)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]


Dot product of A and B:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


# Matrix Function in Numpy Array

1. Transpose
   
3. Swapaxes
   
5. inverse
   
7. Determinate


#  Transpose
""" Converting the Number of columns into rows"""

In [36]:
print("The Matrix A")
A

The Matrix A


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
Transpose_A = np.transpose(A)

Transpose_A

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

#  Swapaxes

In [ ]:

""" Converting the Number of columns into rows and Rows into Columns"""

In [39]:
print("The Marix of B is:")
B

The Marix of B is:


array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [43]:
# Swapaxes of the Matrix B

swap_B = np.swapaxes(B,0,1)
swap_B

array([[9, 6, 3],
       [8, 5, 2],
       [7, 4, 1]])

# Inverse of the Matrix

In [52]:
#  Invering of the Matrix
""" Converting the Position of First Diagonal Values and Sign of the 2nd Diagonal Values """

' Converting the Position of First Diagonal Values and Sign of the 2nd Diagonal Values '

In [53]:
# Inverising of the Matix C

print("The Matrix C befor Inversing")
C = np.matrix([[1,2],[3,4]])

C

The Matrix C befor Inversing


matrix([[1, 2],
        [3, 4]])

In [54]:
# Inverising of the Matix C

print("The Matrix C after Inversing")
Inverse_C = np.linalg.inv(C)   # .linalg ---> Refer linear algebra Module
Inverse_C

The Matrix C after Inversing


matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

# Power
Dot Matrix of the [ Matrix1 ]  * [ Matrix2]

In [56]:
myMatrix = np.matrix([[1,2],[3,4]])

myMatrix

matrix([[1, 2],
        [3, 4]])

In [68]:
# General form of the power
# """General_Form = np.linalg.matrix_power(Matrix, n)""""
# """
    # n = 0, gives the identical Matrix
    # n > 0 , give the power (multiply)
    # n < 0, Inverse Multiply Power   ---- finding determinent, Inverse, adjoin/determint
#""""


#Applying the Power Method in matrix by using the n= 0

pow_myMarix = np.linalg.matrix_power(myMatrix, 0)
pow_myMarix

matrix([[1, 0],
        [0, 1]])

In [67]:
#Applying the Power Method in matrix by using the n= 2

pow_myMarix = np.linalg.matrix_power(myMatrix, 2)
pow_myMarix

matrix([[ 7, 10],
        [15, 22]])

In [66]:
#Applying the Power Method in matrix by using the n= -2
 
pow_myMarix = np.linalg.matrix_power(myMatrix, -2)
pow_myMarix

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

# Determinate

In [70]:
myMatrix = np.matrix([[1,2],[3,4]])
myMatrix

matrix([[1, 2],
        [3, 4]])

In [71]:
Determinent_myMatrix = np.linalg.det(myMatrix)

In [72]:
Determinent_myMatrix

-2.0000000000000004